/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as WhyRouteImport } from './routes/why'
import { Route as WhyUsRouteImport } from './routes/why-us'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/testimonials': typeof TestimonialsRoute
  '/why': typeof WhyRoute
  '/why-us': typeof WhyUsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/testimonials': typeof TestimonialsRoute
  '/why': typeof WhyRoute
  '/why-us': typeof WhyUsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/testimonials': typeof TestimonialsRoute
  '/why': typeof WhyRoute
  '/why-us': typeof WhyUsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/process'
    | '/products'
    | '/testimonials'
    | '/why'
    | '/why-us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/process'
    | '/products'
    | '/testimonials'
    | '/why'
    | '/why-us'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/process'
    | '/products'
    | '/testimonials'
    | '/why'
    | '/why-us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProcessRoute: typeof ProcessRoute
  ProductsRoute: typeof ProductsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WhyRoute: typeof WhyRoute
  WhyUsRoute: typeof WhyUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProcessRoute: ProcessRoute,
  ProductsRoute: ProductsRoute,
  TestimonialsRoute: TestimonialsRoute,
  WhyRoute: WhyRoute,
  WhyUsRoute: WhyUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
